### ISSUE TITLE
Report error instead of aborting when g_bus_get_sync fails

### ISSUE THREAD

**Issue by marler8997** [flatpak/libportal#118]
In `xdp_portal_init`, the `g_bus_get_sync` can fail if a system has not properly set up DBUS.  Instead of aborting, it would be nice if there was a way for the application to detect/handle this error, for example, reporting to the user that DBUS may not have been configured/setup properly.

It seems the reason for calling "abort" here could be because the Glib "init" hook doesn't provide a way to report an error?  Maybe we'd have to add a function to check for errors on an XdpPortal object after it has been initialized?

**Comment by TingPing** [comment]
> the Glib "init" hook doesn't provide a way to report an error?

It does have a way: [`GInitable`](https://developer-old.gnome.org/gio/unstable/GInitable.html).

My assumption is just that it was a shortcut.

*All* of libportal is going to fail without DBus. So every API needs to handle a no-dbus situation and error. This would be a tedious thing to do.

That said I really don't like the `abort()` here. It is bad form for any library.

**Comment by TingPing** [comment]
I guess we don't really need to make every API handle the situation.

Just implement `GInitable`, document that it is the responsibility of applications to check `g_initable_init()` and not use the object if it fails.
