### ISSUE TITLE
Pin a new release

### ISSUE THREAD

**Issue by chereskata** [flatpak/libportal#123]
Hello,

i am the maintainer of `flowtime` ([github](https://github.com/Diego-Ivan/Flowtime)) on Alpine Linux. It also depends on `libportal`. Unfortunately it uses features, that are not available in v0.6 of `libportal`.

Would it be possible to bundle ready made changes over the last year and a half into a new release?

Thank you very much!

**Comment by GeorgesStavracas** [comment]
Sure, it'll happen any time this month

**Comment by chereskata** [comment]
Thank you very much!

**Comment by GeorgesStavracas** [comment]
Done: https://github.com/flatpak/libportal/releases/tag/0.7

**Comment by chereskata** [comment]
Thanks a lot!
