### ISSUE TITLE
Qt 6.5+ does support xdg-foreign

### ISSUE THREAD

**Issue by ilya-fedin** [flatpak/libportal#126]
The comment says `TODO: QtWayland doesn't support xdg-foreign protocol yet` but that's not quite true (moreover, QTBUG-76983 is closed as a duplicate while QTBUG-73801 is about importing a parent, not exporting). Qt 6.5 supports xdg-foreign, it's just there's no public API yet (although I'm not sure they will ever make it public, that's not something regular applications are supposed to use I guess). It could be accessed in such way:
```
	if (const auto services = dynamic_cast<QGenericUnixServices*>(
			QGuiApplicationPrivate::platformIntegration()->services())) {
		handle = g_strdup(services->portalWindowIdentifier(w).toUtf8().constData());
	}
```
The API prefixes the handle with x11:/wayland: doing actually all the _xdp_parent_export_qt's job.
The following includes are needed:
```
#include <qpa/qplatformintegration.h>
#include <private/qguiapplication_p.h>
#include <private/qgenericunixservices_p.h>
```
And a `#if QT_VERSION >= QT_VERSION_CHECK(6, 5, 0)` check perhaps.

Another way is to support xdg-foreign manually with libwayland-client + a custom wl_registry instance using wl_display from `qApp->nativeInterface<QNativeInterface::QWaylandApplication>()->display()` (6.5+) or `reinterpret_cast<wl_display*>(QGuiApplication::platformNativeInterface()->nativeResourceForIntegration(QByteArray("wl_display")))` (5.4.0+ or if replacing "wl_display" with "display" then 5.0.0+). QGuiApplication::platformNativeInterface needs a `#include <qpa/qplatformnativeinterface.h>`.

**Comment by Conan-Kudo** [comment]
WDYT about this, @grulja?

**Comment by Conan-Kudo** [comment]
Feel free to proceed with a PR to add the support for the Qt6 bindings. :)

**Comment by ilya-fedin** [comment]
#135
