### ISSUE TITLE
Specify GLib minimum version

### ISSUE THREAD

**Issue by tintou** [flatpak/libportal#16]
I couldn't build it on elementary 5.1 because `g_hash_table_steal_extended` is missing, it has been added in GLib 2.58 so it might be reasonable to specify 2.58 as the minimal supported version

**Comment by trappedinspacetime** [comment]
Yes, it breaks the compatibility on Ubuntu 16.04. Do we have any chance to port that function to `2.48.2` ?

**Comment by tintou** [comment]
@trappedinspacetime We are patching it in elementary OS (Ubuntu 18.04) to substitute this function and lower our GLib requirements https://github.com/elementary/os-patches/commit/b83fe31ae35ec35b33fe71b79d2a51f5969c2f29

**Comment by trappedinspacetime** [comment]
@tintou Thank you very much. I was thinking of building [GLIB-2.64](http://ftp.gnome.org/pub/gnome/sources/glib/2.64/glib-2.64.0.tar.xz).
and adding its library.
But we have other dependency issues with [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal-gtk) and [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal)

**Comment by hadess** [comment]
> Yes, it breaks the compatibility on Ubuntu 16.04. Do we have any chance to port that function to `glib 2.48.2` ?

There's really no reason to support this old version of Ubuntu, libportal is supposed to be used _inside_ the sandbox, not outside it.
