### ISSUE TITLE
xdp_portal_take_screenshot failing with XDP_SCREENSHOT_FLAG_NONE

### ISSUE THREAD

**Issue by KelvinNovais** [flatpak/libportal#167]
Calling the `xdp_portal_take_screenshot ()` function with the `XDP_SCREENSHOT_FLAG_NONE` returns "Screenshot failed". On the other hand, it works perfectly if you pass the `XDP_SCREENSHOT_FLAG_INTERACTIVE`.

This behavior is only observed when the application is running on a flatpak sandbox; if you compile and run the application on your host operating system, it will work normally (using both flags).

To test this, see the [Screenshot](https://gitlab.gnome.org/gnumdk/screenshot) app; it works normally, but replacing the flag on this [line](https://gitlab.gnome.org/gnumdk/screenshot/-/blob/main/src/screenshot-window.c?ref_type=heads#L85) makes the application return a warning "Screenshot failed". 

---

I tested the versions 0.7.1, 0.8.0 and 0.8.1, all with the same results.

**Comment by GeorgesStavracas** [comment]
Does this issue happen if you use D-Bus directly, without libportal being involved?

**Comment by KelvinNovais** [comment]
I didn't test without libportal, because mixing GVariant and D-Bus calls is a little bit hard.

However, if helpful, I can point [NormCap](https://github.com/dynobo/normcap), it makes a D-Bus call [here](https://github.com/dynobo/normcap/blob/main/normcap/screengrab/handlers/dbus_portal.py#L69).
It has other handlers for taking a screenshots, but at the end it uses D-Bus because it asks for permission at the first time.

**Comment by KelvinNovais** [comment]
> Does this issue happen if you use D-Bus directly, without libportal being involved?

I performed a simple test using only D-Bus, and these are the responses:

I. Running on the host OS:
`(uint32 0, {'uri': <'file:///home/kelvin/Pictures/Screenshot-7.png'>})`

II. Running on a flatpak:
`(uint32 2, @a{sv} {})`

As expected, (I) gets the results successfully, while (II) is returning response = 2 (_the user interaction was ended in some other way_)

**Comment by KelvinNovais** [comment]
I figured out what is the problem:

According to the [documentation](https://libportal.org/method.Portal.take_screenshot.html), `xdp_portal_take_screenshot()` can receive the parameter `parent` as `NULL`, but that only works with the interactive flag.

It would be interesting to explain it on the documentation.

**Comment by KelvinNovais** [comment]
I'm closing the issue.

Recently I tested xdp-portal on fedora 40 and it worked as expected; the previous tests were made on Fedora 39.
