### ISSUE TITLE
XdpPortal:update-progress never called on update

### ISSUE THREAD

**Issue by chergert** [flatpak/libportal#37]
When using the update portal, it is expected that "update-progress" signal is emitted occasionally with status. I don't seem to be getting any calls there during the update which makes progress state look a bit weird in Builder.

**Comment by grulja** [comment]
Took me a while to setup a test app to verify this, but it works for me. This is my debug output:
```
Update started:  true
OnUpdateProgress:  0  status:  0
OnUpdateProgress:  0  status:  0
OnUpdateProgress:  100  status:  0
OnUpdateProgress:  100  status:  2
```
So the update-progress signal is called. It would be nice to see some steps in between, on the other hand this is exactly mentioned in the documentation:

`Gets emitted to indicate progress of the installation.  It's undefined exactly how often this is sent, but it will be emitted at least once at the end with non-zero status field. For each successful operation in the update we're also guaranteed to send one (and only one) signal with progress 100.`

Given my results I think this bug can be closed.
