### ISSUE TITLE
How to detect the state of autostart background in libportal?

### ISSUE THREAD

**Issue by Digitalone1** [flatpak/libportal#51]
Hello everyone.

Through libportal we can request to enable autostart for a specific app. But how can we check if the autostart is enabled for the same app? 

Is there a specific method or process to detect it? I don't see any function to get it and even Gnome ToDo that implements this service is using a gsettings key to track the state rather than ask to libportal, which is not really ideal.

Am I missing something or this is not possible?

**Comment by bilelmoussaoui** [comment]
That is not possible from the Background portal implementation. See https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Background. If such thing has to be implemented in the libportal side, it has to be added first to https://github.com/flatpak/xdg-desktop-portal/
