### ISSUE TITLE
location portal's location-updated signal is never emited

### ISSUE THREAD

**Issue by A6GibKm** [flatpak/libportal#67]
In the following code, the callbacks for `location-updated` are never executed, and the monitor does start correctly. Also reproducible on vala
```python
        # ...
        window.present()

        portal = Xdp.Portal()
        parent = XdpGtk4.parent_new_gtk(window)

        time_threshold = 100
        distance_threshold = 100
        time_threshold = 100
        accuracy = Xdp.LocationAccuracy.CITY
        flags = Xdp.LocationMonitorFlags.NONE
        cancellable = None

        portal.connect("location-updated", (lambda x: print("Location updated")))
        portal.location_monitor_start(
            parent,
            distance_threshold,
            time_threshold,
            accuracy,
            flags,
            cancellable,
            cb,
        )
        
        # ...
     def cb(portal, result):
        try:
            re = portal.location_monitor_start_finish(result)
            print("Portal started:", re)
        except Exception as err: 
            print(err)

```

**Comment by A6GibKm** [comment]
Ditto `xdp_portal_session_monitor_start()`.

**Comment by A6GibKm** [comment]
This is probably related to https://github.com/flatpak/libportal/issues/37.

**Comment by grulja** [comment]
This should be fixed with https://github.com/flatpak/libportal/pull/45. Isn't it?

**Comment by A6GibKm** [comment]
I tried to do this near the date the issue was opened, so probably not.

**Comment by grulja** [comment]
> I tried to do this near the date the issue was opened, so probably not.

And do you use latest git or official releases? Because there was a release made after you opened this bug.

**Comment by A6GibKm** [comment]
Directly from master, unless GNOME Builder played some trick on me where it used an older cache (I don't think so, but it happens from time to time).

**Comment by A6GibKm** [comment]
I can confirm that it is not working on master.

**Comment by grulja** [comment]
Works for me.

I just added a simple code to Qt demo/test we have as part of libportal and I can see it sends the `location-updated` signal. Can you check this on DBus? I don't know Python so maybe you have a bug in your code? Also try to restart xdg-desktop-portal and start it with `G_MESSAGES_DEBUG=all` to see if there are some errors.

**Comment by A6GibKm** [comment]
I tried with vala, python, and the libportal demo (after adding a quick test), the code is executed and returns a success from the start_monitoring operation but the LocationUpdated signal is never emitted on the other side of the DBus.

At least on my laptop, it works fine on the first try of each login session, but then never again. On my desktop it fails randomly.

**Comment by grulja** [comment]
Try to use better precision and smaller threshold. Anyway, if you properly receive the signal at least one time, it means that the code in libportal does its job and there is no issue to be solved. If you have issues with location reporting then you probably need to report an issue in geoclue.

**Comment by A6GibKm** [comment]
Just for the record, unlike the test code above, all the local test are run with `time_threshold = 0`.

On the other hand ASHPD, a rust library to talk with portals, works all the time without any difficulty, so it is neither an issue in xdg-desktop-portals nor in geoclue.

**Comment by grulja** [comment]
Can you share output from `dbus-monitor --session` for both tests (ASHPD and libportal)?

**Comment by A6GibKm** [comment]
Here are the logs:

[ashpd.txt](https://github.com/flatpak/libportal/files/7862128/ashpd.txt)
[libportal.txt](https://github.com/flatpak/libportal/files/7862129/libportal.txt)


The test was made with `distance_threshold=60`, `time_threshold=0, and `LocationAccuracy.CITY``.

**Comment by grulja** [comment]
I think I see the issue. I'll open a PR.

**Comment by grulja** [comment]
For the record, it's a bug in ASHPD and I already talked to @bilelmoussaoui about it. Basically there is a typo in both options so when you set `distance_threshold` and ` time_threshold` it gets ignored and fallbacks to default (which is 0). Both options are actually `distance-threshold` and `time-threshold` → dash vs underscore.
