### ISSUE TITLE
Unable to link

### ISSUE THREAD

**Issue by MGThePro** [flatpak/libportal#89]
So I have a very minimal source file and Makefile, but I keep getting errors when linking and I'm not entirely sure why
this is my capture.c:
```
#include <libportal/portal.h>
int main(int argc, char* argv[]) {
    XdpPortal *portal = xdp_portal_new ();
    return 0;
}
```
And here is my makefile:
```
CFILES := capture.c
CFLAGS := `pkg-config --libs --cflags glib-2.0`

build:
	gcc ${CFILES} ${CFLAGS} -o capture
```
And here is the error when I try to compile this
```
gcc capture.c `pkg-config --libs --cflags glib-2.0` -o capture
/sbin/ld: /tmp/cccGe8I9.o: in function `main':
capture.c:(.text+0x10): undefined reference to `xdp_portal_new'
collect2: error: ld returned 1 exit status
make: *** [Makefile:5: build] Error 1
```
Here's the output I got after compiling it without linking and then running `ld --verbose capture`:
https://pastebin.com/39LSPby0

I've tried using meson as well, but I have no experience with it so I couldn't fix an issue where it wouldn't find gio/gio.h
And even after manually running the build command with the necessary gio stuff included it only created 2 object files which I cant do a whole lot with.

**Comment by smcv** [comment]
> ```
> CFLAGS := `pkg-config --libs --cflags glib-2.0`
> ```

That's only pulling in glib-2.0 as a dependency, not libportal. If you want to depend on libportal, you need `pkg-config --libs --cflags libportal`.
